sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=jswetzen/mysql-backup
  - secure: CuZsm1NHpw62G5BMuQaLtUW8POL/1F9Lm0TZGihoBZqU/f5vw+OS3ChWH5yDyy2pdCRUecrqBcU+LUzYOeO/vRHy2bZfxhnNqT3x7c/atXfikvrIDQ5k1rGg7Nm4fnsUTpQEVnbrhKyF9q8ytNBneLGzZaBy1ZKGHd9rHhDHmhYqBGe0pE6AxRPXarrSaUGI1hyjKcC1gJ7Hy5F6y7UvjLKZNLOfVZEKm+fGLOSAtNXjF3su4tudRUiGUUmM97n7ubs/qXTP9FasuIreH5TVoHiEfTASfhl2zmv8s18SyazHXIrDxcNIK0QBoqOxHf5qiuq4z+xVEYd7zZEQ8M/1jq0BU9ufVipj74PoBK3Az7oZ6PtbXxLVtpmLKHdFCKkXlp7lLw0Tb4rM+ERgIUKe/J7HUOhdJYjzb4exTXvo71D2lmVClZBDq44xhY0p0VznjgT2tHvY62C86hscbHZHVjoSkgbFtSPe9dJX/sg8RKhr7GDlAriPCAQSMUGJ6/AqSVQH2yjDdXQggwLowxqbmsbJVHXLaRDdLIBJ0HVxM1CRZpPsWIMvVolteFv8RpkSEyR4PtVnuLUrJrSBXT1xJtPIy90KN6E0xZKaV0AL4pEaDiJfquNZJu56sG7hik03gr+ufAogONHujKTymv6ylJivnj3Y1mjwQJP0rm6ynLM=
  - secure: Hm73mhUQPGaAtsR25/+1Ctn5ViQbrxdGEfm65vLxkyExJb2q9p0x/y4plVdRjn6OEREYTiQw7wsWYelfbVScqTiGSXwGXA4xArQWC8Ho6Zr3Ir81CvTyCGWGzJgW2MPNDQlxuuEgvRoiP5FrRGBCjU5gsyw/O2tHy2+6SE0p2JV4mD8Zjr66ajPNQh4Bjf8e8tBYykscBztWlyYr0IUeYKP4Pw56S5CdTK97GriMigCrhPskrA63Ch82VBIU8ts1odys2IXcXMq5ARZ5xUuoTzeZaUW6hfBXFa7dBhMmCHBJxvE3gukE9sdZI8/i7Xw0EfkgiY4NB5rqDUwq/kcgndXB7bhmebf8sxxwrHqRUQHgXPSkuwc7E7QnXzu+LIb8h135ULnBbPEq21qQs8OgcVBk/Ii/CivrFCMzMpSwZk2bP9UKneTVswVOApz6QHoc70dWW9Mmowjx5BHQIshS7BrdHkeM862S2WafgZDQnzZaxg68hiAKRRR4/dyEmg5qz4lpLH4CZ8HBwqh+hvPs3gT9QQo5yZSxQ3+oqhu3Xs9pTcjXryu/iRt2hcaKMvPtZvUCbPMQnXCUjtmeIa/QuCgNWssarBbAZYbJvW1PHDUozKfzeNKC3iUjaPB0SCBcWn2iiR5+Pr5P9k8FKw1A77gPYjgLnhlnuQj8LjuVlEQ=
script:
- docker build -f Dockerfile -t $REPO:$COMMIT .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
