name: Docker Image CI

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/vertical-evolution-v3vo-ab/postgres-backup/postgres-backup:latest
